In [1]:
from scipy.sparse import load_npz
import numpy as np

In [12]:
adj_matrix = load_npz("./sparse_connectivity_matrix.npz")

In [13]:
adj_matrix.nnz

15091983

In [6]:
adj_matrix.data

array([2, 2, 2, ..., 1, 1, 1], shape=(15091983,), dtype=int8)

In [9]:
# Threshold the sparse matrix to obtain a binary adjacency matrix
adj_matrix.data = (adj_matrix.data > 0).astype(np.int8)

In [10]:
adj_matrix.data

array([1, 1, 1, ..., 1, 1, 1], shape=(15091983,), dtype=int8)

In [2]:
matrix_info = np.load("./sparse_connectivity_matrix.npz", mmap_mode='r')

In [3]:
matrix_info["data"]

array([2, 2, 2, ..., 1, 1, 1], shape=(15091983,), dtype=int8)

In [5]:
matrix_info["shape"]

array([138639, 138639])

In [11]:
np.nonzero(matrix_info)

(array([0, 1, 2, 3, 4]),)